/**
 * Validation Schemas - Central Export
 *
 * This file provides a central point to import all validation schemas and utilities.
 * Import from here to access validation functions across the application.
 */

// Config validation exports
export {
  azureOpenAIConfigSchema,
  standardOpenAIConfigSchema,
  openAIConfigSchema,
  azureEnvSchema,
  standardEnvSchema,
  environmentVariablesSchema,
  validEnvironmentSchema,
  validateEnvironmentVariables,
  buildOpenAIConfig,
  validateDeploymentName,
  validateApiVersion,
  validateEndpoint,
  safeValidateEnvironment,
  formatValidationError,
  type AzureOpenAIConfig,
  type StandardOpenAIConfig,
  type OpenAIConfig,
  type EnvironmentVariables,
} from './config';

// Template validation exports
export {
  outputFormatSchema,
  templateCategorySchema,
  outputTypeSchema,
  lucideIconSchema,
  templateSectionSchema,
  templateSectionInputSchema,
  templateSchema,
  templateInputSchema,
  templateUpdateSchema,
  defaultTemplateConfigSchema,
  validateTemplateInput,
  validateTemplateSection,
  validateTemplateSectionInput,
  validateTemplate,
  validateTemplateUpdate,
  validateOutputFormat,
  validateTemplateCategory,
  validateOutputType,
  validateLucideIcon,
  safeValidateTemplateInput,
  safeValidateTemplateSection,
  getCommonLucideIcons,
  isOutputFormat,
  isTemplateCategory,
  isOutputType,
  type OutputFormat,
  type TemplateCategory,
  type OutputType,
  type TemplateSection,
  type TemplateSectionInput,
  type Template,
  type TemplateInput,
  type TemplateUpdate,
  type DefaultTemplateConfig,
} from './template';

// Transcript validation exports
export {
  transcriptionStatusSchema,
  transcriptSegmentSchema,
  transcriptMetadataSchema,
  transcriptSchema,
  transcriptInputSchema,
  transcriptUpdateSchema,
  transcriptionProgressSchema,
  fileUploadSchema,
  validateTranscriptSegment,
  validateTranscriptMetadata,
  validateTranscript,
  validateTranscriptInput,
  validateTranscriptUpdate,
  validateTranscriptionProgress,
  validateFileUpload,
  validateTranscriptionStatus,
  safeValidateFileUpload,
  safeValidateTranscript,
  isSupportedAudioType,
  hasSupportedAudioExtension,
  getSupportedAudioTypes,
  getSupportedAudioExtensions,
  getMaxFileSize,
  getMaxFileSizeMB,
  isValidFileSize,
  isValidDuration,
  isTranscriptionStatus,
  type TranscriptionStatus,
  type TranscriptSegment,
  type TranscriptMetadata,
  type Transcript,
  type TranscriptInput,
  type TranscriptUpdate,
  type TranscriptionProgress,
  type FileUpload,
  type FileProcessingPlan,
} from './transcript';
